### ISSUE TITLE
[Question] Problem sets from 2008 to 2014

### ISSUE THREAD

**Issue by yetian** [google/coding-competitions-archive#2]
From the coding competition website, it is possible to see the problem sets from 2008. Do you plan to archive them here as well?

**Comment by stoman** [comment]
The problem sets so far include only Hash Code, which was created in 2014. This is the complete set of all Hash Code problems.

Problems for Code Jam and Kick Start might be added later.

**Comment by yetian** [comment]
Awesome, thank you @stoman @tbuzzelli
