### ISSUE TITLE
Ranklist / Standings

### ISSUE THREAD

**Issue by code-chaser** [google/coding-competitions-archive#7]
- Not exactly an issue. Just wanted to know where can I find the standings archive for the competitions?
- Because the older links to standings don't seem to work anymore.
- They are not dumped, right? Riiiight? 😢

**Comment by bvd0** [comment]
Unofficial archive: https://zibada.guru/gcj/
(See https://codeforces.com/blog/entry/113809 for more info.)

**Comment by code-chaser** [comment]
Great work, @bvd0!
It's amazing what all can be done, playing with the raw data.
Thanks for keeping these memories safe.
I miss them like anything. When they were there, didn't participate as actively as I could have, now just being an old man filled with regret. 😭 Meh!
Anyways, keep up the good work. 👍🏻

**Comment by code-chaser** [comment]
Also, out of nowhere, if any opportunity opens up 🤑🤑, I'm yet another great software developer with all that great stuff, you know, DSA, OOPs, analytical thinking, problem-solving, logic building, teamwork, time-management, adaptability, versatility, other synonyms. And I know all the programming languages before I join the team. After joining, I'll be good with JAVA, C++ and after a little practice, Python.
Jokes apart, I'm a great coder with enough hunger for software development 💻  to skip meals 🍚  resolving chains of bugs 🐞  and still not getting tired.
For further reference, [Resume](https://drive.google.com/file/d/1mWYouNdZ9VPr9ar1DfuW2IA4pUlwI6qr/view) | [LinkedIn](https://www.linkedin.com/in/yashvardhan-baid/).
Thanks & Regards,
Yashvardhan
